<#
.SYNOPSIS
  Копирует аватары ботов и их список из src/cse/ в runtime/.

.DESCRIPTION
  Идемпотентный скрипт: повторный запуск безопасно перезаписывает целевые файлы.
  Источник: src/cse/cstrike/gfx/cse/avatars/*      -> runtime/cstrike/gfx/cse/avatars/*
  Перед копированием список src/cse/cstrike/scripts/CseBotAvatars.txt
  генерируется заново по PNG/TGA-файлам из каталога аватаров.

.PARAMETER DryRun
  Только показать, что будет скопировано, без записи.

.PARAMETER Root
  Корень репозитория (по умолчанию — родитель папки tools/).
#>
[CmdletBinding()]
param(
  [switch]$DryRun,
  [string]$Root
)

$ErrorActionPreference = 'Stop'

# $PSScriptRoot недоступен в значениях param() по умолчанию (PS 5.1 + CmdletBinding)
if (-not $Root) { $Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path }

$srcImages = Join-Path $Root 'src\cse\cstrike\gfx\cse\avatars'
$srcList   = Join-Path $Root 'src\cse\cstrike\scripts\CseBotAvatars.txt'
$dstImages = Join-Path $Root 'runtime\cstrike\gfx\cse\avatars'
$dstList   = Join-Path $Root 'runtime\cstrike\scripts\CseBotAvatars.txt'

if (-not (Test-Path -LiteralPath $srcImages)) {
  Write-Error "Source not found: $srcImages"
  exit 1
}

$supportedExtensions = @('.png', '.tga')
$maxAvatars = 256
$allFiles = @(Get-ChildItem -Path $srcImages -File | Sort-Object Name)
$avatarFiles = @($allFiles |
  Where-Object { $supportedExtensions -contains $_.Extension.ToLowerInvariant() })
$skippedFiles = @($allFiles |
  Where-Object { $supportedExtensions -notcontains $_.Extension.ToLowerInvariant() })

foreach ($file in $skippedFiles) {
  Write-Warning "Skipped unsupported avatar file: $($file.Name)"
}
if ($avatarFiles.Count -gt $maxAvatars) {
  Write-Warning "Found $($avatarFiles.Count) avatars; the client uses only the first $maxAvatars entries."
  $avatarFiles = @($avatarFiles | Select-Object -First $maxAvatars)
}

$listLines = @(
  '// Generated by tools\install_bot_avatars.ps1. Do not edit manually.'
  '// Add PNG/TGA files to src/cse/cstrike/gfx/cse/avatars/.'
  '// Format: TGA32 or PNG 64x64; JPG is not supported.'
  '// Client limit: 256 entries.'
  ''
  '"CseBotAvatars"'
  '{'
)
$listLines += @($avatarFiles | ForEach-Object {
  '    "gfx/cse/avatars/{0}"' -f $_.Name
})
$listLines += '}'
$listContent = ($listLines -join [Environment]::NewLine) + [Environment]::NewLine

if ($DryRun) {
  Write-Output "DRY: generate $($avatarFiles.Count) avatar entries -> $srcList"
}
else {
  $utf8NoBom = New-Object -TypeName System.Text.UTF8Encoding -ArgumentList $false
  [System.IO.File]::WriteAllText($srcList, $listContent, $utf8NoBom)
  Write-Output "OK: generated cstrike/scripts/CseBotAvatars.txt ($($avatarFiles.Count) entries)"
}

$copied = 0

$avatarFiles | ForEach-Object {
  $target = Join-Path $dstImages $_.Name

  if ($DryRun) {
    Write-Output "DRY: $($_.FullName) -> $target"
    return
  }

  if (-not (Test-Path -LiteralPath $dstImages)) {
    New-Item -ItemType Directory -Path $dstImages -Force | Out-Null
  }

  Copy-Item -LiteralPath $_.FullName -Destination $target -Force
  Write-Output "OK: cstrike/gfx/cse/avatars/$($_.Name)"
  $copied++
}

if ($DryRun) {
  Write-Output "DRY: $srcList -> $dstList"
}
else {
  $dstListDir = Split-Path $dstList -Parent
  if (-not (Test-Path -LiteralPath $dstListDir)) {
    New-Item -ItemType Directory -Path $dstListDir -Force | Out-Null
  }

  Copy-Item -LiteralPath $srcList -Destination $dstList -Force
  Write-Output 'OK: cstrike/scripts/CseBotAvatars.txt'
  $copied++
}

Write-Output ""
Write-Output "Copied: $copied file(s)"
if ($DryRun) { Write-Output "(dry-run - no files were written)" }
