maps/de_afghan_r.txt
sound/ambience/afghan/afheliflyby2.wav
sound/ambience/afghan/afwind.wav
sound/ambience/afghan/afdesert.wav
sound/ambience/afghan/afscorp_hunt2.wav
sound/ambience/afghan/aftruck.wav
sound/ambience/afghan/afdog.wav
sound/ambience/afghan/afmusic.wav
sound/ambience/afghan/afap_rotor.wav
sound/ambience/afghan/afwindStreet.wav
models/uplant1.mdl
models/uplant1t.mdl
models/hubi.mdl
overviews/de_afghan_r.bmp
overviews/de_afghan_r.txt
gfx/env/sierra_bk.tga
gfx/env/sierra_dn.tga
gfx/env/sierra_ft.tga
gfx/env/sierra_lf.tga
gfx/env/sierra_rt.tga
gfx/env/sierra_up.tga